// modules - encapsulated code(only share the minumum)
//CommonJS, every file is module (by default)
const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative flavor')
require('./7-mind-grenade')
sayHi('susan')
/ayHi(names.john)
sayHi(names.peter)